export const codesMap = new Map([
    [0, ['Clear sky', 'clear']],
    [1, ['Mainly clear', 'mostly_cloudy']],
    [2, ['Partly cloudy', 'mostly_cloudy']],
    [3, ['Overcast', 'cloudy']],
    [45, ['Fog', 'fog']],
    [48, ['Depositing rime fog', 'fog']],
    [51, ['Light drizzle', 'light_rain']],
    [53, ['Moderate drizzle', 'light_rain']],
    [55, ['Dense drizzle', 'light_rain']],
    [61, ['Light rain', 'rain']],
    [63, ['Moderate rain', 'rain']],
    [65, ['Heavy rain', 'rain']],
    [66, ['Freezing rain', 'rain']],
    [67, ['Heavy freezing rain', 'rain']],
    [71, ['Light snow fall', 'light_snow']],
    [73, ['Moderate snow fall', 'light_snow']],
    [75, ['Heavy snow fall', 'snow']],
    [77, ['Snow grains', 'snow']],
    [80, ['Light rain shower', 'rain']],
    [81, ['Moderate rain shower', 'rain']],
    [82, ['Heavy rain shower', 'rain']],
    [85, ['Light snow shower', 'snow']],
    [86, ['Heavy snow shower', 'snow']],
    [95, ['Thunderstorm', 'storm']],
    [96, ['Thunderstorm with light hail', 'storm']],
    [99, ['Thunderstorm with heavy hail', 'storm']]
])